export enum EnvNames {
  SERVER_HTTP_PORT = "HTTP_PORT",
  SERVER_SOCKET_PORT = "SOCKET_PORT",

  MONGODB_URI = "MONGODB_URI",

  RABBITMQ_HOST = "RABBITMQ_HOST",
  RABBITMQ_PORT = "RABBITMQ_PORT",
  RABBITMQ_EVENT_BUS_NAME = "RABBITMQ_EVENT_BUS_NAME",

  GCLOUD_PROJECT_ID = "GCLOUD_PROJECT_ID",
  GCLOUD_CLIENT_EMAIL = "GCLOUD_CLIENT_EMAIL",
  GCLOUD_PRIVATE_KEY = "GCLOUD_PRIVATE_KEY",

  GCLOUD_STORAGE_BUCKET_NAME = "GCLOUD_STORAGE_BUCKET_NAME",
}
